version: "3"

services:
  backend:
    build: .
    container_name: backendrcp
    restart: unless-stopped
    environment:
      DATABASE_URI: "mongodb://mongodb:27017/local"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - rcp-enfermeria
    ports:
      - "1337:1337"

  mongodb:
    image: mongo
    container_name: mongoexample
    restart: unless-stopped
    networks:
      - rcp-enfermeria
    volumes:
      - strapidata:/data/db
    ports:
      - "27017:27017"

networks:
  rcp-enfermeria:
    driver: bridge

volumes:
  strapidata:
